version: '2'
services:
  redis:
    image: 'redis:7.0.9-alpine3.17'
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass $REDIS_PASSWORD
  sso-auth-helper:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - SSO_PROVIDER_SECRET=${SSO_PROVIDER_SECRET}
      - DISCOURSE_ROOT_URL=${DISCOURSE_ROOT_URL}
      - NONCE_EXPIRES_IN_SECONDS=${NONCE_EXPIRES_IN_SECONDS}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
